workdir: ./

station: SF_0003
pred_hour: 3
target_name: hj_label_${pred_hour}
fog_threahold: 1
topk: 4
time_limit: 60 # change to large value like 3000. unit: seconds
distill_time_limit: 60

report_dest: data/report/dissipation_summary.xlsx
stat_dest: data/report/dissipation_stat.xlsx
importance_dest: data/report/dissipation_importance.xlsx
model_path: data/model/${station}_${pred_hour}.onnx
info_path: data/model/${station}_${pred_hour}.json

station_name:
  SF_0001: 부산항
  SF_0002: 부산항신항
  SF_0003: 인천항
  SF_0004: 평택당진항
  SF_0005: 군산항
  SF_0006: 대산항
  SF_0007: 목포항
  SF_0008: 여수광양항
  SF_0009: 해운대
  SF_0010: 울산항
  SF_0011: 포항항




